### ISSUE TITLE
resizable data table columns

### ISSUE THREAD

**Issue by wc-matteo** [tusen-ai/naive-ui#1569]
### This function solves the problem (这个功能解决的问题)
allowing the user to select at runtime the best column size for their needs
### Expected API (期望的 API)
probably a boolean prop to allow the column resize

**Comment by 07akioni** [comment]
We will consider it.

**Comment by fcloud89** [comment]
> We will consider it.

@07akioni 老哥，就你一个人在维护组件库啊，有点难顶哦

**Comment by Bulkman** [comment]
Need this feature as well

**Comment by Bulkman** [comment]
Implemented resizable columns is this[gist](https://gist.github.com/Bulkman/c375ca138a50809a50c7f304c5bd4a52). It turned out to be not so hard.

Some preparations must be done to use it:
1) global style override
`th.n-data-table-th {
    padding: 0 !important;
}`
2) Each resizable column defenition in array must be liko so:
`{
    key: 'rate',
    title: createResizableColumnTitle('Rate'),
    width: 150
}` 
It has to have width!
3) Columns must be reactive e.g `const columns = reactive(createColumns());`
4) usage of scroll-x prop is not recommended as all columns width defined

**Comment by litt1e-p** [comment]
@Bulkman hi, will you share a demo for it?

**Comment by houqiangxie** [comment]
> 
你这方案不行啊，拖动了表格线还是不动

**Comment by funkindy** [comment]
Hello! Thanks for the amazing library. Any plans/updates on column resize feature? Thank you.

**Comment by equt** [comment]
track in #3165
