### ISSUE TITLE
加载Spin组件 圆圈动画有毛刺感

### ISSUE THREAD

**Issue by aboutZZ** [tusen-ai/naive-ui#3556]
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome 104.0.5112.81

### System and its version (系统及其版本)
Win 10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/spin

### Reappearance steps (重现步骤)
使用加载 Spin组件

### Expected results (期望的结果)
——

### Actual results (实际的结果)
Spin的圆圈感觉不平滑，有很多凸起的像素，给人造成毛刺感

### Remarks (补充说明)
![loading gif](https://s3.bmp.ovh/imgs/2022/08/20/dd371f44a2dc0ae0.gif)

仔细看也能发现 时不时有个灰色小像素块在圆圈轨迹上出现

**Comment by Sepush** [comment]
这是一个已知问题 在低分辨率(1080)的 windows 系统上应该是必现的

**Comment by eagleoflqj** [comment]
iOS也能看见那个灰色块

**Comment by Sepush** [comment]
这个问题是上次为了修 https://github.com/tusen-ai/naive-ui/issues/2506 在 n-base-loading 实现里用了三个 svg 在旋转动画的时候有错位和抖动 然后导致看起来会有毛刺感 暂时我还不知道怎么修🧐

**Comment by re-ovo** [comment]
win11, 2k屏，也有这个问题

**Comment by suica** [comment]
Strange fur is due to `stroke-dasharray` value, which cuts the whole circle into several pieces.
And the blinking "gray pixels" is due to that the two rotating circle are not exactly match in frequency.
One can observe this with a very heavy stroke.
![spin1](https://github.com/tusen-ai/naive-ui/assets/8041462/88a0e498-d5b7-45b0-b84a-53aed37a57db)
The original implementation (before the fix of #2506) is pretty good and has none of those issues, so i modified the original implementation to make the animation work with the call of blocking methods.
