### ISSUE TITLE
Why `n-select` trigger `on-create` on input event?

### ISSUE THREAD

**Issue by hansonfang** [tusen-ai/naive-ui#4375]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome all version

### System and its version (系统及其版本)
macOS

### Reappearance link (重现链接)
https://codesandbox.io/s/agitated-raman-yhpdl4?file=/src/Demo.vue

### Reappearance steps (重现步骤)
click select input then input something

### Expected results (期望的结果)
on-create callback function should be triggered on hit enter instead of random key input.

### Actual results (实际的结果)
on-create callback function was triggered on input event.

**Comment by amadeus711** [comment]
Your judgment is affected by the name of this API. In fact, this API means to create *options* rather than *tags*. If you want to get the newly created *tag*, you need to use `@update:value`. The params of this API are in order. The last item is the newly selected tag. You need to compare it with option to see if it is created by the user.

**Comment by hansonfang** [comment]
ok，thanks for the response.
