### ISSUE TITLE
选择器 Select 异步加载（单选）问题

### ISSUE THREAD

**Issue by xuelingfei** [tusen-ai/naive-ui#4625]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.13

### Browser and its version (浏览器及其版本)
Chrome(111)

### System and its version (系统及其版本)
Windows(10)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/select#remote.vue

### Reappearance steps (重现步骤)
1.输入搜索关键词 'Drive'，下拉框呈现一条搜索结果 'Drive My Car'
2.点击其他区域使选择器失去焦点，此时选择器内搜索关键词 'Drive' 会被自动清除
3.重新点击选择器，此时无搜索关键词，但下拉框仍呈现之前的搜索结果 'Drive My Car'

### Expected results (期望的结果)
点击其他区域使选择器失去焦点时保留搜索关键词 'Drive'
或者
重新点击选择器时调用远程搜索对应函数重新获取下拉框选项

### Actual results (实际的结果)
选择器失去焦点时保留了搜索结果，却没有保留搜索条件

**Comment by amadeus711** [comment]
When using remote, all states of `Select` will be controlled by the user. Refer to:
https://codesandbox.io/s/funny-nash-il4qdo?file=/src/Demo.vue

**Comment by xuelingfei** [comment]
But the default logic of the filter is inconvenient and confused for the user.

**Comment by NightGreyMoon** [comment]
I'm facing the same issue here, @xuelingfei any solution found? Thanks!
And when I'm dealing with editing scenario, there is value bound for Select's value, it becomes even more weird: value displayed in the input of select (not label, because of the binding), and "no data" is showed when clicking the select

编辑的时候体验更加怪怪的，因为绑定了 value， Select 控件的输入框会显示之前选中的选项的 value（不是 label），点击 Select 控件以后，识别不了当前的值（会变灰色，类似 placeholder），下拉列表会显示“No Data”
@xuelingfei  请问你有碰到类似问题，有啥建议吗

**Comment by NightGreyMoon** [comment]
> > I'm facing the same issue here, @xuelingfei any solution found? Thanks! And when I'm dealing with editing scenario, there is value bound for Select's value, it becomes even more weird: value displayed in the input of select (not label, because of the binding), and "no data" is showed when clicking the select
> > 编辑的时候体验更加怪怪的，因为绑定了 value， Select 控件的输入框会显示之前选中的选项的 value（不是 label），点击 Select 控件以后，识别不了当前的值（会变灰色，类似 placeholder），下拉列表会显示“No Data” @xuelingfei 请问你有碰到类似问题，有啥建议吗
> 
> 有预设值的时候最好不要用异步加载。

好的，谢啦
