### ISSUE TITLE
When there is only a `slider` in the `model`, there is a problem with the `tooltip` positioning of the `slider`

### ISSUE THREAD

**Issue by oyal** [tusen-ai/naive-ui#4756]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(105.0.5195.127)

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/relaxed-chandrasekhar-zjmel6?file=/src/App.vue

### Reappearance steps (重现步骤)
点击按钮打开Modal，拖动Slider，Tooltip才会归位，再次打开依旧会有这个问题

### Expected results (期望的结果)
打开Modal不应该显示Slider的Tooltip

### Actual results (实际的结果)
打开Modal在卡片外部显示了Slider的Tooltip

### Remarks (补充说明)

![image](https://user-images.githubusercontent.com/88022434/233773631-efc2c8e6-24ae-48a6-879e-36367e6eb256.png)

**Comment by amadeus711** [comment]
这个问题是由于组件库对 a11y 的处理造成的，`modal` 打开后默认会聚焦到里面的元素，而 `slider` 被聚焦时，会显示 `tooltip`。当 `modal` 内只有 `slider` 一个组件时，默认就会造成 `tooltip` 的定位出现问题。有两个解决方案：
1. 设置 `modal` 的 `auto-focus`  属性为 `false`。
2. 将 `slider` 的 `tooltip` 默认设置为 `false`，等到 `modal` 打开后或在合适的时机下再将其设置为 `true`。
第一种解决方案的参考：https://codesandbox.io/s/sharp-bassi-d2z8bh?file=/src/App.vue

This issue is caused by the processing of a11y by the component library. When the `modal` is opened, it will default to focusing on the elements inside, while when the `slider` is focused, it will display `tooltip`. When there is only one component in the `modal`, the default will cause problems with the positioning of the `tooltip`. There are two solutions:
1. Set the `modal`'s `auto-focus` prop to `false`.
2. Set the `slider`'s `tooltip` prop to `false` by default, and wait until `modal` is opened or at an appropriate time to set `tooltip` prop to `true` again.
Reference for the first solution: https://codesandbox.io/s/sharp-bassi-d2z8bh?file=/src/App.vue

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
