### ISSUE TITLE
The values of the Cascader sub-options are the same, which prevents selection.

### ISSUE THREAD

**Issue by ottocsb** [tusen-ai/naive-ui#5076]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
103

### System and its version (系统及其版本)
win

### Node version (Node 版本)
18

### Reappearance link (重现链接)
https://codesandbox.io/s/determined-sun-gdfs9t?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Open the option to trigger it.

### Expected results (期望的结果)
When the values of the child options within a parent option are the same as those of other parent options, it is possible to make a correct selection because their parent option values are different.

### Actual results (实际的结果)
I don't understand why different values in the parent options would trigger this issue when the values in the child options are the same. What is the underlying logic behind it?

**Comment by suica** [comment]
We just assume the value of every option is unique.
You can use [treemate](https://github.com/07akioni/treemate) to manage your tree data (since it is already a dep of naive-ui).
For example, assign a unique key (and value) for every node, and give the tree data to treemate. Then invoke `TreeMate.getPath(key, options?)` to get the path to a leaf node: you will obtain an array containing similar to `["grade3", "unit4"]`.

P.S. it is a more common practice to let the backend to assign unique keys for nodes. But it will also be acceptable to do it in frontend given that the set of options is not subject to change.

**Comment by ottocsb** [comment]
thanks
