### ISSUE TITLE
数据表格删除选中数据后被删除的数据还出现在选中列表中

### ISSUE THREAD

**Issue by oohmygosh** [tusen-ai/naive-ui#5555]
### TuSimple/naive-ui version (版本)
2.37.0

### Vue version (Vue 版本)
3.3.7

### Browser and its version (浏览器及其版本)
Chrome(120.0.6099.131)

### System and its version (系统及其版本)
Windows11

### Reappearance link (重现链接)
https://codesandbox.io/embed/amazing-bird-5fcpdc?fontsize=14&hidenavigation=1&theme=dark

### Reappearance steps (重现步骤)
如题

### Expected results (期望的结果)
删除选中数据后选中列表中不应该再出现

### Actual results (实际的结果)
删除后被删除的key还是出现在了选中列表

**Comment by thibodeauxjl** [comment]
So selected items in the table creates a separate array of data which is defined in your example as "checkedRowKeys". When you select a row, this key is pushed to that array. Remove a record from "data" doesn't remove it from "checkedRowKeys". You would need to create a function that accurately deletes whatever is selected instead of using the Array.prototype.pop() and in that function, you would remove it from both "data" as well as "checkedRowKeys".

**Comment by oohmygosh** [comment]
> So selected items in the table creates a separate array of data which is defined in your example as "checkedRowKeys". When you select a row, this key is pushed to that array. Removing a record from the "data" array doesn't remove it from "checkedRowKeys" array. You would need to create a function that accurately deletes whatever is selected instead of using the Array.prototype.pop() and in that function you would remove it from both "data" as well as "checkedRowKeys".

Thank you. I see
